In [1]:
# Assignment #4: Text Generation (Seq2Seq) Performance Analysis
# Task: Compare Google vs Facebook/Meta translator on Eng→Ur dataset using BLEU + ROUGE.

print("Assignment #4: Seq2Seq Performance Analysis (Eng→Ur)")
print("Metrics: BLEU + ROUGE, Model outputs: Google Translator, Meta (M2M100)")

Assignment #4: Seq2Seq Performance Analysis (Eng→Ur)
Metrics: BLEU + ROUGE, Model outputs: Google Translator, Meta (M2M100)

**Install dependencies**

In [2]:
!pip -q install deep-translator sacrebleu evaluate transformers sentencepiece accelerate pandas
print("Dependencies installed")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.4 MB/s eta 0:00:00
Dependencies installed

**Imports**

In [3]:
import os, json, zipfile
from typing import List, Optional, Tuple, Dict

import pandas as pd
import torch

from deep_translator import GoogleTranslator
import sacrebleu
import evaluate

from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

**Upload ZIP in Colab**

In [7]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

print("Accessing: Urdu_Eng_Dataset.zip from Google Drive")

# Set path to your ZIP file
zip_path = "/content/drive/MyDrive/Datasets/Urdu_Eng_Dataset.zip"

# Check if file exists
if not os.path.exists(zip_path):
    raise FileNotFoundError("ZIP file not found in Drive. Please check the path.")

print("File found:", zip_path)

Mounted at /content/drive
Accessing: Urdu_Eng_Dataset.zip from Google Drive
File found: /content/drive/MyDrive/Datasets/Urdu_Eng_Dataset.zip

**Unzip dataset**

In [8]:
extract_dir = "Urdu_Eng_Dataset"
os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_dir)

print("Unzipped to:", extract_dir)

# Show extracted files
all_files = []
for root, _, files_ in os.walk(extract_dir):
    for fn in files_:
        all_files.append(os.path.join(root, fn))

print("Files found:")
for f in all_files[:50]:
    print(" -", f)
if len(all_files) > 50:
    print(f"... and {len(all_files)-50} more")

Unzipped to: Urdu_Eng_Dataset
Files found:
 - Urdu_Eng_Dataset/english-corpus.txt
 - Urdu_Eng_Dataset/urdu-corpus.txt
 - Urdu_Eng_Dataset/__MACOSX/._urdu-corpus.txt
 - Urdu_Eng_Dataset/__MACOSX/._english-corpus.txt

**Load dataset (auto-detect file)**

In [9]:
def pick_main_file(files_list: List[str]) -> str:
    supported = [f for f in files_list if f.lower().endswith((".csv", ".tsv", ".jsonl", ".json", ".txt"))]
    if not supported:
        raise FileNotFoundError(" No supported file found (csv/tsv/json/jsonl/txt).")
    supported.sort(key=lambda p: os.path.getsize(p), reverse=True)
    return supported[0]

data_path = pick_main_file(all_files)
print("Auto-selected dataset file:", data_path)

# Load based on extension
low = data_path.lower()
if low.endswith(".csv"):
    df_raw = pd.read_csv(data_path)
elif low.endswith(".tsv"):
    df_raw = pd.read_csv(data_path, sep="\t")
elif low.endswith(".jsonl"):
    rows = []
    with open(data_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    df_raw = pd.DataFrame(rows)
elif low.endswith(".json"):
    with open(data_path, "r", encoding="utf-8") as f:
        obj = json.load(f)
    df_raw = pd.DataFrame(obj if isinstance(obj, list) else obj.get("data", obj))
else:
    # txt fallback: try "English<TAB>Urdu"
    rows = []
    with open(data_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if "\t" in line:
                a, b = line.split("\t", 1)
                rows.append({"english": a.strip(), "urdu": b.strip()})
    df_raw = pd.DataFrame(rows)

print("Loaded shape:", df_raw.shape)
print("Columns:", list(df_raw.columns))
df_raw.head()

Auto-selected dataset file: Urdu_Eng_Dataset/urdu-corpus.txt
Loaded shape: (0, 0)
Columns: []

Empty DataFrame
Columns: []
Index: []

**Detect English + Urdu columns (clean)**

In [10]:
import os
import pandas as pd

#  Change only if your unzip folder name is different
DATA_DIR = "Urdu_Eng_Dataset"   # same folder you used in unzip cell

def find_file_by_keywords(root: str, keywords: list[str]) -> str:
    """
    Find a file inside root directory whose filename contains all keywords (case-insensitive).
    Example: keywords=["english", "corpus"] matches english-corpus.txt
    """
    keywords = [k.lower() for k in keywords]
    matches = []
    for dirpath, _, filenames in os.walk(root):
        for fn in filenames:
            name = fn.lower()
            if all(k in name for k in keywords):
                matches.append(os.path.join(dirpath, fn))
    if not matches:
        raise FileNotFoundError(f"Could not find file with keywords {keywords} inside {root}")
    # pick the largest match (usually main file)
    matches.sort(key=lambda p: os.path.getsize(p), reverse=True)
    return matches[0]

# Auto-find both files
en_path = find_file_by_keywords(DATA_DIR, ["english"])
ur_path = find_file_by_keywords(DATA_DIR, ["urdu"])

print("English file:", en_path)
print("Urdu file   :", ur_path)

def read_lines(path: str) -> list[str]:
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        lines = [line.strip() for line in f if line.strip()]
    return lines

english_lines = read_lines(en_path)
urdu_lines = read_lines(ur_path)

print("English lines:", len(english_lines))
print("Urdu lines   :", len(urdu_lines))

min_len = min(len(english_lines), len(urdu_lines))
if len(english_lines) != len(urdu_lines):
    print("Warning: line counts differ. Using first", min_len, "pairs only.")

df = pd.DataFrame({
    "english": english_lines[:min_len],
    "urdu_ref": urdu_lines[:min_len],
})

# Clean
df["english"] = df["english"].astype(str).str.strip()
df["urdu_ref"] = df["urdu_ref"].astype(str).str.strip()
df = df[(df["english"].str.len() > 0) & (df["urdu_ref"].str.len() > 0)].reset_index(drop=True)

print("Final usable rows:", len(df))
df.head(10)

English file: Urdu_Eng_Dataset/english-corpus.txt
Urdu file   : Urdu_Eng_Dataset/urdu-corpus.txt
English lines: 24525
Urdu lines   : 24524
Warning: line counts differ. Using first 24524 pairs only.
Final usable rows: 24524

                 english                   urdu_ref
0    is zain your nephew      زین تمہارا بھتیجا ہے۔
1   i wish youd trust me  کاش تم مجھ پر بھروسہ کرتے
2       did he touch you      کیا اس نے آپ کو چھوا؟
3       its part of life         اس کی زندگی کا حصہ
4         zain isnt ugly        زین بدصورت نہیں ہے۔
5   above all be patient       سب سے بڑھ کر صبر کرو
6  i learned it from him    میں نے اسے اس سے سیکھا۔
7    why am i doing this     میں یہ کیوں کر رہا ہوں
8  i made a bad decision   میں نے ایک برا فیصلہ کیا
9         zain wont care      زین پرواہ نہیں کرے گا

**Google Translator setup + translate function**

In [11]:
from deep_translator import GoogleTranslator

# Google Translator object (EN -> UR)
google_translator = GoogleTranslator(source="en", target="ur")

def translate_google(text: str) -> str:
    """
    Translate one English sentence to Urdu using Google (deep-translator).
    If translation fails, return "" so pipeline continues.
    """
    text = str(text).strip()
    if not text:
        return ""
    try:
        return google_translator.translate(text) or ""
    except Exception:
        return ""

print("Google translator ready")
print("Demo:", translate_google("My name is Ali."))

Google translator ready
Demo: میرا نام علی ہے۔

**Facebook/Meta Translator (Seq2Seq) setup**

In [12]:
import torch
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

# Device select (GPU  fast)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Load tokenizer + model
tok = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")
model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M").to(device)
model.eval()

# Set source language English and force output language Urdu
tok.src_lang = "en"
forced_bos_token_id_ur = tok.get_lang_id("ur")

def translate_meta_batch(texts, max_new_tokens: int = 128, num_beams: int = 4):
    """
    Translate a batch of English sentences to Urdu using Meta M2M100.
    """
    texts = [str(t).strip() for t in texts]
    enc = tok(texts, return_tensors="pt", padding=True, truncation=True).to(device)

    with torch.no_grad():
        out = model.generate(
            **enc,
            forced_bos_token_id=forced_bos_token_id_ur,
            max_new_tokens=max_new_tokens,
            num_beams=num_beams
        )

    return [x.strip() for x in tok.batch_decode(out, skip_special_tokens=True)]

print("Meta (Facebook) translator ready")
print("Demo:", translate_meta_batch(["My name is Humera."])[0])

Device: cuda

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/298 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentencepiece.bpe.model:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/233 [00:00<?, ?B/s]

Meta (Facebook) translator ready
Demo: میرا نام ہومرا ہے

In [13]:
print("Rows:", len(df))
print("Columns:", list(df.columns))
print("Missing English:", df["english"].isna().sum())
print("Missing Urdu Ref:", df["urdu_ref"].isna().sum())

# quick sample for class
display(df.sample(5, random_state=42))

Rows: 24524
Columns: ['english', 'urdu_ref']
Missing English: 0
Missing Urdu Ref: 0

                           english                          urdu_ref
14443  it’s very thoughtful of you                 کیا وہ بھائی ہیں؟
24319            zain has ambition           میں نے رسی کو چھوڑ دیا۔
12678            you may enter now             زین نے مجھے گلے لگایا
24423          my dad will kill me             وہ انگریزی پڑھاتی ہے۔
19977         i havent got all day  کیا میں آپ کو گانا چلا سکتا ہوں؟

**Run translations on full dataset (Google + Meta) and store in df**

In [14]:
import os
import pandas as pd

os.makedirs("outputs", exist_ok=True)

GOOGLE_FILE = "outputs/google.csv"
META_FILE   = "outputs/meta.csv"

# -------------------- Google (save + resume) --------------------
if os.path.exists(GOOGLE_FILE):
    google_preds = pd.read_csv(GOOGLE_FILE)["pred"].astype(str).tolist()
    print("Loaded Google saved rows:", len(google_preds))
else:
    google_preds = []
    print("No Google cache found, starting from 0")

total = len(df)

for i in range(len(google_preds), total):
    if i % 50 == 0:
        print(f"Google resume: {i}/{total}")
    google_preds.append(translate_google(df.loc[i, "english"]))

    # Save every 50 rows (safe)
    if (i + 1) % 50 == 0:
        pd.DataFrame({"pred": google_preds}).to_csv(GOOGLE_FILE, index=False, encoding="utf-8-sig")

# Final save
pd.DataFrame({"pred": google_preds}).to_csv(GOOGLE_FILE, index=False, encoding="utf-8-sig")
df["urdu_google"] = google_preds
print("Google done:", len(google_preds))


# -------------------- Meta (save + resume) --------------------
if os.path.exists(META_FILE):
    meta_preds = pd.read_csv(META_FILE)["pred"].astype(str).tolist()
    print("Loaded Meta saved rows:", len(meta_preds))
else:
    meta_preds = []
    print("No Meta cache found, starting from 0")

texts = df["english"].tolist()
batch_size = 32 if device == "cuda" else 8

for i in range(len(meta_preds), len(texts), batch_size):
    if i % 512 == 0:
        print(f"Meta resume: {i}/{len(texts)}")
    meta_preds.extend(translate_meta_batch(texts[i:i + batch_size]))

    # Save every ~1024 rows
    if len(meta_preds) % 1024 < batch_size:
        pd.DataFrame({"pred": meta_preds}).to_csv(META_FILE, index=False, encoding="utf-8-sig")

pd.DataFrame({"pred": meta_preds}).to_csv(META_FILE, index=False, encoding="utf-8-sig")
df["urdu_meta"] = meta_preds
print("Meta done:", len(meta_preds))

# Preview
df[["english", "urdu_ref", "urdu_google", "urdu_meta"]].head(10)

No Google cache found, starting from 0
Google resume: 0/24524
Google resume: 50/24524
Google resume: 100/24524
Google resume: 150/24524
Google resume: 200/24524
Google resume: 250/24524
Google resume: 300/24524
Google resume: 350/24524
Google resume: 400/24524
Google resume: 450/24524
Google resume: 500/24524
Google resume: 550/24524
Google resume: 600/24524
Google resume: 650/24524
Google resume: 700/24524
Google resume: 750/24524
Google resume: 800/24524
Google resume: 850/24524
Google resume: 900/24524
Google resume: 950/24524
Google resume: 1000/24524
Google resume: 1050/24524
Google resume: 1100/24524
Google resume: 1150/24524
Google resume: 1200/24524
Google resume: 1250/24524
Google resume: 1300/24524
Google resume: 1350/24524
Google resume: 1400/24524
Google resume: 1450/24524
Google resume: 1500/24524
Google resume: 1550/24524
Google resume: 1600/24524
Google resume: 1650/24524
Google resume: 1700/24524
Google resume: 1750/24524
Google resume: 1800/24524
Google resume: 1850/24524
Google resume: 1900/24524
Google resume: 1950/24524
Google resume: 2000/24524
Google resume: 2050/24524
Google resume: 2100/24524
Google resume: 2150/24524
Google resume: 2200/24524
Google resume: 2250/24524
Google resume: 2300/24524
Google resume: 2350/24524
Google resume: 2400/24524
Google resume: 2450/24524
Google resume: 2500/24524
Google resume: 2550/24524
Google resume: 2600/24524
Google resume: 2650/24524
Google resume: 2700/24524
Google resume: 2750/24524
Google resume: 2800/24524
Google resume: 2850/24524
Google resume: 2900/24524
Google resume: 2950/24524
Google resume: 3000/24524
Google resume: 3050/24524
Google resume: 3100/24524
Google resume: 3150/24524
Google resume: 3200/24524
Google resume: 3250/24524
Google resume: 3300/24524
Google resume: 3350/24524
Google resume: 3400/24524
Google resume: 3450/24524
Google resume: 3500/24524
Google resume: 3550/24524
Google resume: 3600/24524
Google resume: 3650/24524
Google resume: 3700/24524
Google resume: 3750/24524
Google resume: 3800/24524
Google resume: 3850/24524
Google resume: 3900/24524
Google resume: 3950/24524
Google resume: 4000/24524
Google resume: 4050/24524
Google resume: 4100/24524
Google resume: 4150/24524
Google resume: 4200/24524
Google resume: 4250/24524
Google resume: 4300/24524
Google resume: 4350/24524
Google resume: 4400/24524
Google resume: 4450/24524
Google resume: 4500/24524
Google resume: 4550/24524
Google resume: 4600/24524
Google resume: 4650/24524
Google resume: 4700/24524
Google resume: 4750/24524
Google resume: 4800/24524
Google resume: 4850/24524
Google resume: 4900/24524
Google resume: 4950/24524
Google resume: 5000/24524
Google resume: 5050/24524
Google resume: 5100/24524
Google resume: 5150/24524
Google resume: 5200/24524
Google resume: 5250/24524
Google resume: 5300/24524
Google resume: 5350/24524
Google resume: 5400/24524
Google resume: 5450/24524
Google resume: 5500/24524
Google resume: 5550/24524
Google resume: 5600/24524
Google resume: 5650/24524
Google resume: 5700/24524
Google resume: 5750/24524
Google resume: 5800/24524
Google resume: 5850/24524
Google resume: 5900/24524
Google resume: 5950/24524
Google resume: 6000/24524
Google resume: 6050/24524
Google resume: 6100/24524
Google resume: 6150/24524
Google resume: 6200/24524
Google resume: 6250/24524
Google resume: 6300/24524
Google resume: 6350/24524
Google resume: 6400/24524
Google resume: 6450/24524
Google resume: 6500/24524
Google resume: 6550/24524
Google resume: 6600/24524
Google resume: 6650/24524
Google resume: 6700/24524
Google resume: 6750/24524
Google resume: 6800/24524
Google resume: 6850/24524
Google resume: 6900/24524
Google resume: 6950/24524
Google resume: 7000/24524
Google resume: 7050/24524
Google resume: 7100/24524
Google resume: 7150/24524
Google resume: 7200/24524
Google resume: 7250/24524
Google resume: 7300/24524
Google resume: 7350/24524
Google resume: 7400/24524
Google resume: 7450/24524
Google resume: 7500/24524
Google resume: 7550/24524
Google resume: 7600/24524
Google resume: 7650/24524
Google resume: 7700/24524
Google resume: 7750/24524
Google resume: 7800/24524
Google resume: 7850/24524
Google resume: 7900/24524
Google resume: 7950/24524
Google resume: 8000/24524
Google resume: 8050/24524
Google resume: 8100/24524
Google resume: 8150/24524
Google resume: 8200/24524
Google resume: 8250/24524
Google resume: 8300/24524
Google resume: 8350/24524
Google resume: 8400/24524
Google resume: 8450/24524
Google resume: 8500/24524
Google resume: 8550/24524
Google resume: 8600/24524
Google resume: 8650/24524
Google resume: 8700/24524
Google resume: 8750/24524
Google resume: 8800/24524
Google resume: 8850/24524
Google resume: 8900/24524
Google resume: 8950/24524
Google resume: 9000/24524
Google resume: 9050/24524
Google resume: 9100/24524
Google resume: 9150/24524
Google resume: 9200/24524
Google resume: 9250/24524
Google resume: 9300/24524
Google resume: 9350/24524
Google resume: 9400/24524
Google resume: 9450/24524
Google resume: 9500/24524
Google resume: 9550/24524
Google resume: 9600/24524
Google resume: 9650/24524
Google resume: 9700/24524
Google resume: 9750/24524
Google resume: 9800/24524
Google resume: 9850/24524
Google resume: 9900/24524
Google resume: 9950/24524
Google resume: 10000/24524
Google resume: 10050/24524
Google resume: 10100/24524
Google resume: 10150/24524
Google resume: 10200/24524
Google resume: 10250/24524
Google resume: 10300/24524
Google resume: 10350/24524
Google resume: 10400/24524
Google resume: 10450/24524
Google resume: 10500/24524
Google resume: 10550/24524
Google resume: 10600/24524
Google resume: 10650/24524
Google resume: 10700/24524
Google resume: 10750/24524
Google resume: 10800/24524
Google resume: 10850/24524
Google resume: 10900/24524
Google resume: 10950/24524
Google resume: 11000/24524
Google resume: 11050/24524
Google resume: 11100/24524
Google resume: 11150/24524
Google resume: 11200/24524
Google resume: 11250/24524
Google resume: 11300/24524
Google resume: 11350/24524
Google resume: 11400/24524
Google resume: 11450/24524
Google resume: 11500/24524
Google resume: 11550/24524
Google resume: 11600/24524
Google resume: 11650/24524
Google resume: 11700/24524
Google resume: 11750/24524
Google resume: 11800/24524
Google resume: 11850/24524
Google resume: 11900/24524
Google resume: 11950/24524
Google resume: 12000/24524
Google resume: 12050/24524
Google resume: 12100/24524
Google resume: 12150/24524
Google resume: 12200/24524
Google resume: 12250/24524
Google resume: 12300/24524
Google resume: 12350/24524
Google resume: 12400/24524
Google resume: 12450/24524
Google resume: 12500/24524
Google resume: 12550/24524
Google resume: 12600/24524
Google resume: 12650/24524
Google resume: 12700/24524
Google resume: 12750/24524
Google resume: 12800/24524
Google resume: 12850/24524
Google resume: 12900/24524
Google resume: 12950/24524
Google resume: 13000/24524
Google resume: 13050/24524
Google resume: 13100/24524
Google resume: 13150/24524
Google resume: 13200/24524
Google resume: 13250/24524
Google resume: 13300/24524
Google resume: 13350/24524
Google resume: 13400/24524
Google resume: 13450/24524
Google resume: 13500/24524
Google resume: 13550/24524
Google resume: 13600/24524
Google resume: 13650/24524
Google resume: 13700/24524
Google resume: 13750/24524
Google resume: 13800/24524
Google resume: 13850/24524
Google resume: 13900/24524
Google resume: 13950/24524
Google resume: 14000/24524
Google resume: 14050/24524
Google resume: 14100/24524
Google resume: 14150/24524
Google resume: 14200/24524
Google resume: 14250/24524
Google resume: 14300/24524
Google resume: 14350/24524
Google resume: 14400/24524
Google resume: 14450/24524
Google resume: 14500/24524
Google resume: 14550/24524
Google resume: 14600/24524
Google resume: 14650/24524
Google resume: 14700/24524
Google resume: 14750/24524
Google resume: 14800/24524
Google resume: 14850/24524
Google resume: 14900/24524
Google resume: 14950/24524
Google resume: 15000/24524
Google resume: 15050/24524
Google resume: 15100/24524
Google resume: 15150/24524
Google resume: 15200/24524
Google resume: 15250/24524
Google resume: 15300/24524
Google resume: 15350/24524
Google resume: 15400/24524
Google resume: 15450/24524
Google resume: 15500/24524
Google resume: 15550/24524
Google resume: 15600/24524
Google resume: 15650/24524
Google resume: 15700/24524
Google resume: 15750/24524
Google resume: 15800/24524
Google resume: 15850/24524
Google resume: 15900/24524
Google resume: 15950/24524
Google resume: 16000/24524
Google resume: 16050/24524
Google resume: 16100/24524
Google resume: 16150/24524
Google resume: 16200/24524
Google resume: 16250/24524
Google resume: 16300/24524
Google resume: 16350/24524
Google resume: 16400/24524
Google resume: 16450/24524
Google resume: 16500/24524
Google resume: 16550/24524
Google resume: 16600/24524
Google resume: 16650/24524
Google resume: 16700/24524
Google resume: 16750/24524
Google resume: 16800/24524
Google resume: 16850/24524
Google resume: 16900/24524
Google resume: 16950/24524
Google resume: 17000/24524
Google resume: 17050/24524
Google resume: 17100/24524
Google resume: 17150/24524
Google resume: 17200/24524
Google resume: 17250/24524
Google resume: 17300/24524
Google resume: 17350/24524
Google resume: 17400/24524
Google resume: 17450/24524
Google resume: 17500/24524
Google resume: 17550/24524
Google resume: 17600/24524
Google resume: 17650/24524
Google resume: 17700/24524
Google resume: 17750/24524
Google resume: 17800/24524
Google resume: 17850/24524
Google resume: 17900/24524
Google resume: 17950/24524
Google resume: 18000/24524
Google resume: 18050/24524
Google resume: 18100/24524
Google resume: 18150/24524
Google resume: 18200/24524
Google resume: 18250/24524
Google resume: 18300/24524
Google resume: 18350/24524
Google resume: 18400/24524
Google resume: 18450/24524
Google resume: 18500/24524
Google resume: 18550/24524
Google resume: 18600/24524
Google resume: 18650/24524
Google resume: 18700/24524
Google resume: 18750/24524
Google resume: 18800/24524
Google resume: 18850/24524
Google resume: 18900/24524
Google resume: 18950/24524
Google resume: 19000/24524
Google resume: 19050/24524
Google resume: 19100/24524
Google resume: 19150/24524
Google resume: 19200/24524
Google resume: 19250/24524
Google resume: 19300/24524
Google resume: 19350/24524
Google resume: 19400/24524
Google resume: 19450/24524
Google resume: 19500/24524
Google resume: 19550/24524
Google resume: 19600/24524
Google resume: 19650/24524
Google resume: 19700/24524
Google resume: 19750/24524
Google resume: 19800/24524
Google resume: 19850/24524
Google resume: 19900/24524
Google resume: 19950/24524
Google resume: 20000/24524
Google resume: 20050/24524
Google resume: 20100/24524
Google resume: 20150/24524
Google resume: 20200/24524
Google resume: 20250/24524
Google resume: 20300/24524
Google resume: 20350/24524
Google resume: 20400/24524
Google resume: 20450/24524
Google resume: 20500/24524
Google resume: 20550/24524
Google resume: 20600/24524
Google resume: 20650/24524
Google resume: 20700/24524
Google resume: 20750/24524
Google resume: 20800/24524
Google resume: 20850/24524
Google resume: 20900/24524
Google resume: 20950/24524
Google resume: 21000/24524
Google resume: 21050/24524
Google resume: 21100/24524
Google resume: 21150/24524
Google resume: 21200/24524
Google resume: 21250/24524
Google resume: 21300/24524
Google resume: 21350/24524
Google resume: 21400/24524
Google resume: 21450/24524
Google resume: 21500/24524
Google resume: 21550/24524
Google resume: 21600/24524
Google resume: 21650/24524
Google resume: 21700/24524
Google resume: 21750/24524
Google resume: 21800/24524
Google resume: 21850/24524
Google resume: 21900/24524
Google resume: 21950/24524
Google resume: 22000/24524
Google resume: 22050/24524
Google resume: 22100/24524
Google resume: 22150/24524
Google resume: 22200/24524
Google resume: 22250/24524
Google resume: 22300/24524
Google resume: 22350/24524
Google resume: 22400/24524
Google resume: 22450/24524
Google resume: 22500/24524
Google resume: 22550/24524
Google resume: 22600/24524
Google resume: 22650/24524
Google resume: 22700/24524
Google resume: 22750/24524
Google resume: 22800/24524
Google resume: 22850/24524
Google resume: 22900/24524
Google resume: 22950/24524
Google resume: 23000/24524
Google resume: 23050/24524
Google resume: 23100/24524
Google resume: 23150/24524
Google resume: 23200/24524
Google resume: 23250/24524
Google resume: 23300/24524
Google resume: 23350/24524
Google resume: 23400/24524
Google resume: 23450/24524
Google resume: 23500/24524
Google resume: 23550/24524
Google resume: 23600/24524
Google resume: 23650/24524
Google resume: 23700/24524
Google resume: 23750/24524
Google resume: 23800/24524
Google resume: 23850/24524
Google resume: 23900/24524
Google resume: 23950/24524
Google resume: 24000/24524
Google resume: 24050/24524
Google resume: 24100/24524
Google resume: 24150/24524
Google resume: 24200/24524
Google resume: 24250/24524
Google resume: 24300/24524
Google resume: 24350/24524
Google resume: 24400/24524
Google resume: 24450/24524
Google resume: 24500/24524
Google done: 24524
No Meta cache found, starting from 0
Meta resume: 0/24524
Meta resume: 512/24524
Meta resume: 1024/24524
Meta resume: 1536/24524
Meta resume: 2048/24524
Meta resume: 2560/24524
Meta resume: 3072/24524
Meta resume: 3584/24524
Meta resume: 4096/24524
Meta resume: 4608/24524
Meta resume: 5120/24524
Meta resume: 5632/24524
Meta resume: 6144/24524
Meta resume: 6656/24524
Meta resume: 7168/24524
Meta resume: 7680/24524
Meta resume: 8192/24524
Meta resume: 8704/24524
Meta resume: 9216/24524
Meta resume: 9728/24524
Meta resume: 10240/24524
Meta resume: 10752/24524
Meta resume: 11264/24524
Meta resume: 11776/24524
Meta resume: 12288/24524
Meta resume: 12800/24524
Meta resume: 13312/24524
Meta resume: 13824/24524
Meta resume: 14336/24524
Meta resume: 14848/24524
Meta resume: 15360/24524
Meta resume: 15872/24524
Meta resume: 16384/24524
Meta resume: 16896/24524
Meta resume: 17408/24524
Meta resume: 17920/24524
Meta resume: 18432/24524
Meta resume: 18944/24524
Meta resume: 19456/24524
Meta resume: 19968/24524
Meta resume: 20480/24524
Meta resume: 20992/24524
Meta resume: 21504/24524
Meta resume: 22016/24524
Meta resume: 22528/24524
Meta resume: 23040/24524
Meta resume: 23552/24524
Meta resume: 24064/24524
Meta done: 24524

,english,urdu_ref,urdu_google,urdu_meta
0,is zain your nephew,زین تمہارا بھتیجا ہے۔,زین تمہارا بھتیجا ہے۔,تمہاری بہن بہن ہے
1,i wish youd trust me,کاش تم مجھ پر بھروسہ کرتے,کاش تم مجھ پر بھروسہ کرتے,میں چاہتا ہوں کہ نوجوان مجھے بھروسہ کریں
2,did he touch you,کیا اس نے آپ کو چھوا؟,کیا اس نے آپ کو چھوا؟,وہ تمہیں لمس کرتی ہے
3,its part of life,اس کی زندگی کا حصہ,اس کی زندگی کا حصہ,زندگی کا حصہ
4,zain isnt ugly,زین بدصورت نہیں ہے۔,زین بدصورت نہیں ہے۔,زینب برا نہیں ہے
5,above all be patient,سب سے بڑھ کر صبر کرو,سب سے بڑھ کر صبر کرو,سب سے پہلے صبر کرنا
6,i learned it from him,میں نے اسے اس سے سیکھا۔,میں نے اسے اس سے سیکھا۔,میں نے اس سے سیکھا
7,why am i doing this,میں یہ کیوں کر رہا ہوں,میں یہ کیوں کر رہا ہوں,میں یہ کیوں کرتا ہوں
8,i made a bad decision,میں نے ایک برا فیصلہ کیا,میں نے ایک برا فیصلہ کیا,میں نے ایک برا فیصلہ کیا
9,zain wont care,زین پرواہ نہیں کرے گا,زین پرواہ نہیں کرے گا,زینب کی دیکھ بھال

**Quick check**

In [15]:
print("Rows:", len(df))
print("Missing urdu_google:", df["urdu_google"].isna().sum())
print("Missing urdu_meta  :", df["urdu_meta"].isna().sum())
df[["english", "urdu_ref", "urdu_google", "urdu_meta"]].head(5)

Rows: 24524
Missing urdu_google: 0
Missing urdu_meta  : 0

,english,urdu_ref,urdu_google,urdu_meta
0,is zain your nephew,زین تمہارا بھتیجا ہے۔,زین تمہارا بھتیجا ہے۔,تمہاری بہن بہن ہے
1,i wish youd trust me,کاش تم مجھ پر بھروسہ کرتے,کاش تم مجھ پر بھروسہ کرتے,میں چاہتا ہوں کہ نوجوان مجھے بھروسہ کریں
2,did he touch you,کیا اس نے آپ کو چھوا؟,کیا اس نے آپ کو چھوا؟,وہ تمہیں لمس کرتی ہے
3,its part of life,اس کی زندگی کا حصہ,اس کی زندگی کا حصہ,زندگی کا حصہ
4,zain isnt ugly,زین بدصورت نہیں ہے۔,زین بدصورت نہیں ہے۔,زینب برا نہیں ہے

**BLEU per sentence + Average BLEU**

In [18]:
import sacrebleu

def sentence_bleu(pred: str, ref: str) -> float:
    return float(sacrebleu.sentence_bleu(str(pred), [str(ref)]).score)

df["bleu_google"] = [sentence_bleu(p, r) for p, r in zip(df["urdu_google"], df["urdu_ref"])]
df["bleu_meta"]   = [sentence_bleu(p, r) for p, r in zip(df["urdu_meta"], df["urdu_ref"])]

avg_bleu_google = float(df["bleu_google"].mean())
avg_bleu_meta   = float(df["bleu_meta"].mean())

print("Average BLEU (Google):", round(avg_bleu_google, 4))
print("Average BLEU (Meta)  :", round(avg_bleu_meta, 4))

Average BLEU (Google): 13.8202
Average BLEU (Meta)  : 6.2135

**ROUGE**

In [19]:
!pip -q install rouge_score
print("rouge_score installed")

  Preparing metadata (setup.py) ... done
  Building wheel for rouge_score (setup.py) ... done
rouge_score installed

In [31]:
import re
from collections import Counter
import numpy as np

def normalize_ur(s: str) -> str:
    s = str(s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def tokens(s: str):
    return normalize_ur(s).split()

def ngrams(toks, n: int):
    return [tuple(toks[i:i+n]) for i in range(0, max(0, len(toks)-n+1))]

def f1(p: float, r: float) -> float:
    return 0.0 if (p + r) == 0 else (2 * p * r) / (p + r)

def rouge_n_f1(pred: str, ref: str, n: int) -> float:
    pt = tokens(pred)
    rt = tokens(ref)
    if len(pt) == 0 or len(rt) == 0:
        return 0.0

    p_ng = Counter(ngrams(pt, n))
    r_ng = Counter(ngrams(rt, n))
    overlap = sum((p_ng & r_ng).values())

    p_total = sum(p_ng.values())
    r_total = sum(r_ng.values())
    if p_total == 0 or r_total == 0:
        return 0.0

    prec = overlap / p_total
    rec = overlap / r_total
    return f1(prec, rec)

def lcs_length(a, b) -> int:
    # LCS length for token lists (O(n*m) DP). Works fine for short sentences.
    n, m = len(a), len(b)
    dp = [0] * (m + 1)
    for i in range(1, n + 1):
        prev = 0
        for j in range(1, m + 1):
            tmp = dp[j]
            if a[i-1] == b[j-1]:
                dp[j] = prev + 1
            else:
                dp[j] = max(dp[j], dp[j-1])
            prev = tmp
    return dp[m]

def rouge_l_f1(pred: str, ref: str) -> float:
    pt = tokens(pred)
    rt = tokens(ref)
    if len(pt) == 0 or len(rt) == 0:
        return 0.0
    lcs = lcs_length(pt, rt)
    prec = lcs / len(pt)
    rec = lcs / len(rt)
    return f1(prec, rec)

def rouge_scores_avg(preds, refs):
    r1, r2, rL = [], [], []
    for p, r in zip(preds, refs):
        r1.append(rouge_n_f1(p, r, 1))
        r2.append(rouge_n_f1(p, r, 2))
        rL.append(rouge_l_f1(p, r))
    return {
        "rouge1": float(np.mean(r1)),
        "rouge2": float(np.mean(r2)),
        "rougeL": float(np.mean(rL)),
    }

rouge_google = rouge_scores_avg(df["urdu_google"].tolist(), df["urdu_ref"].tolist())
rouge_meta   = rouge_scores_avg(df["urdu_meta"].tolist(), df["urdu_ref"].tolist())

print("Urdu-friendly ROUGE (Google):", rouge_google)
print("Urdu-friendly ROUGE (Meta)  :", rouge_meta)

Urdu-friendly ROUGE (Google): {'rouge1': 0.16567121859340872, 'rouge2': 0.12070000631391872, 'rougeL': 0.16525669248996688}
Urdu-friendly ROUGE (Meta)  : {'rouge1': 0.11286330086917917, 'rouge2': 0.041723676610179866, 'rougeL': 0.11149154668577746}

**Final comments (which is better?)**

In [33]:
def winner(a: float, b: float) -> str:
    if abs(a - b) < 1e-9:
        return "Tie"
    return "Google" if a > b else "Meta (Facebook/M2M100)"

print("BLEU winner   :", winner(avg_bleu_google, avg_bleu_meta))
print("ROUGE-L winner:", winner(rouge_google["rougeL"], rouge_meta["rougeL"]))

print(f"- Average BLEU shows {winner(avg_bleu_google, avg_bleu_meta)} performs better on this Eng→Ur dataset.")
print(f"- Urdu-friendly ROUGE-L shows {winner(rouge_google['rougeL'], rouge_meta['rougeL'])} performs better in overlap/recall.")

BLEU winner   : Google
ROUGE-L winner: Google
- Average BLEU shows Google performs better on this Eng→Ur dataset.
- Urdu-friendly ROUGE-L shows Google performs better in overlap/recall.

**Save results**

In [34]:
import os
import json
from google.colab import files

os.makedirs("outputs", exist_ok=True)

out_csv = "outputs/final_translation_results.csv"
df.to_csv(out_csv, index=False, encoding="utf-8-sig")

summary = {
    "num_samples": len(df),
    "avg_bleu_google": float(avg_bleu_google),
    "avg_bleu_meta": float(avg_bleu_meta),

    # clearer keys (Urdu-friendly ROUGE)
    "urdu_friendly_rouge_google": rouge_google,
    "urdu_friendly_rouge_meta": rouge_meta,
}

with open("outputs/final_summary.json", "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2, ensure_ascii=False)

print("Saved:", out_csv, "and outputs/final_summary.json")

files.download(out_csv)
files.download("outputs/final_summary.json")

Saved: outputs/final_translation_results.csv and outputs/final_summary.json